Фильтрация меток на карте
htmlacademy-javascript/958445-keksobooking-21 pull request #11
Opened 2020-11-07 20:36 UTC by PatricCormac

2020-11-08 18:16 UTC, artem-Zrilov requested changes
При выборе другого фильтра предыдущий слетает это не должно быть, лучше фильтрацию объедений в одну функцию и при каждом выборе пункта фильтровать

2020-11-09 05:36 UTC, artem-Zrilov requested changes

2020-11-09 05:36 UTC, artem-Zrilov commented on js/filters.js
> +    return filteredAds.concat(housingTypeFilter()).concat(housingPriceFilter()).concat(housingRoomsFilter()).concat(housingGuestsFilter()).concat(housingFeaturesFilter());
Запись совершено не читаемая, и по моему у тебя в таком виде в массиве появляются дубли

2020-11-09 05:36 UTC, artem-Zrilov commented on js/filters.js
> +        return item.offer.features.includes(housingFeatures.querySelectorAll(`input:checked`)[i].value);
Тут тоже скорее всего не верно работает, так как будет возвращен элемент по первому вхождению элемента, а элементов может быть несколько

2020-11-09 07:20 UTC, PatricCormac commented on js/filters.js
> +    return filteredAds.concat(housingTypeFilter()).concat(housingPriceFilter()).concat(housingRoomsFilter()).concat(housingGuestsFilter()).concat(housingFeaturesFilter());
Да. Тут есть дубли, но я проверяю их по количеству повторений, и те, у которых число повторений самое большое попадают в начало массива, а дальше я вывожу на экран первые пять.

2020-11-09 07:30 UTC, artem-Zrilov commented on js/filters.js
> +    return filteredAds.concat(housingTypeFilter()).concat(housingPriceFilter()).concat(housingRoomsFilter()).concat(housingGuestsFilter()).concat(housingFeaturesFilter());
Не думаю что это должно так работать. Проще всего просто через .filter() и просто правильно условия прописать

2020-11-09 15:55 UTC, merged